### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by kenshin000** [kenshin000/protospac-38376#1]
https://serene-falls-36967.herokuapp.com/

**Comment by shodai-ito** [comment]
@kenshin000 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
#### **`プロトタイプ編集機能`**
- [x] **正しく編集できた場合は、詳細ページへ遷移すること**
編集が完了するとトップページへ遷移してしまいます。

#### **`ユーザー詳細機能`**
- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
トップページ及びユーザー詳細ページのプロトタイプ投稿者名をクリックすると、ログインユーザーの詳細ページへ遷移してしまいます。
また、コメント投稿者名をクリックするとトップページへリダイレクトされてしまいます。
<img width="420" alt="スクリーンショット 2022-08-15 9 21 48" src="https://user-images.githubusercontent.com/62537107/184560518-40250cb3-841d-4027-8537-f1fe0a229137.png">

- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
一部ユーザー名の表示が未編集となっております。
<img width="589" alt="スクリーンショット 2022-08-15 9 21 13" src="https://user-images.githubusercontent.com/62537107/184560511-d7fdeb3c-38fd-442b-a9d3-e35795ab0b74.png">

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by kenshin000** [comment]
確認ありがとうございます。

修正完了いたしましたので今一度確の程お願いいたします。

**Comment by motomuun** [comment]
@kenshin000 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回依頼した箇所が修正されておりませんでした。
改めて以下のご確認をお願いします！
また、修正出来ている場合は、デプロイが正しく完了しているかのご確認もお願いいたします。

[修正依頼箇所]
**プロトタイプ編集機能**

- [ ] **正しく編集できた場合は、詳細ページへ遷移すること**
編集して「保存する」ボタンを押すと、トップページに遷移します。詳細ページに遷移するように修正をお願いします。

**ユーザー詳細機能**

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
コメント投稿者をクリックすると、トップページに遷移します。ユーザーの詳細ページに遷移するように修正をお願いします。
<img width="1433" alt="スクリーンショット 2022-08-15 14 48 47" src="https://user-images.githubusercontent.com/65059944/184583546-36fb116b-17fc-4b48-b544-f37456c820dc.png">


- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
以下の赤枠にユーザー名が表示されるところ、「ユーザー名さん」と表示されています。正しいユーザー名が表示されるように修正をお願いします。
<img width="1437" alt="スクリーンショット 2022-08-15 14 52 40" src="https://user-images.githubusercontent.com/65059944/184583402-ef697494-62b5-4b1f-97df-1048bc0d11ae.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by kenshin000** [comment]
申し訳ありませんデプロイができていませんでした。
実行しましたので、ご確認の程お願いいたします。

**Comment by shodai-ito** [comment]
@kenshin000 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
